chiaratinmazian/Poulax

app/controllers/application_controller.rb, app/models/hen.rb, app/models/reservation.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, db/migrate/20191126094147_create_hens.rb, db/migrate/20191126094417_create_reservations.rb, db/migrate/20191126095926_add_default_value_to_accepted.rb, db/migrate/20191126100635_add_username_to_users.rb, db/schema.rb, test/models/hen_test.rb, test/models/reservation_test.rb
We added the models(user, reservation, hen), the validations and tested them
=> added the models

Gemfile, Gemfile.lock, db/seeds.rb
Hey girls ! I  just created the seeds to complete our database with data test. Can you check it please.
=> Seeds successfully created

app/controllers/hens_controller.rb, db/seeds.rb, test/controllers/hens_controller_test.rb
I created the controller-hens files
=> controller-hens created

app/controllers/users_controller.rb, test/controllers/users_controller_test.rb
just added je files for the users controller
=> added userscontroller files

app/controllers/hens_controller.rb, app/controllers/users_controller.rb
controllers hens and users deleted
=> error fixed

app/controllers/hens_controller.rb, app/views/hens/index.html.erb, app/views/hens/show.html.erb, config/routes.rb
Hens controller added with routes index/show + views index/show
=> hens routes added with actions in controller

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Co-authored-by: amelie <amelie.dedovic@gmail.com>
Co-authored-by: christy <christy.michel@sfr.fr>
Check component et css (form, button,etc...)
=> frontend-form-ok

app/controllers/hens_controller.rb, app/controllers/reservations_controller.rb, app/views/hens/show.html.erb, app/views/reservations/new.html.erb, config/routes.rb, test/controllers/reservations_controller_test.rb
Added controller reservations + action new and create +view new
=> Reservations new create

app/controllers/pages_controller.rb, app/controllers/reservations_controller.rb, app/models/reservation.rb, app/views/reservations/new.html.erb
Action new and create added and working. Can you check the code anyway ?
=> Reservations actions

app/controllers/hens_controller.rb, app/views/hens/new.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb
Dashboard added in controller pages, route ok, + action new and create in hens controller to check
=> Dashboard route

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/views/hens/index.html.erb
=> index-done

Gemfile, Gemfile.lock, app/controllers/hens_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/hen.rb, app/views/hens/index.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, db/migrate/20191128102403_add_coordinates_to_hens.rb, db/schema.rb, package.json, yarn.lock
=> Gecocoder install

app/controllers/hens_controller.rb, app/views/hens/edit.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb, db/seeds.rb
i added the edit update and destroy actions 
we can do this from the dashboard only
=> added edit update and destroy action

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/views/hens/index.html.erb, app/views/hens/show.html.erb
Check index and show for the map!
=> index show map ok

app/assets/stylesheets/components/_card.scss, app/views/hens/index.html.erb, app/views/hens/show.html.erb
check the container in the index!
=> index show corrigé

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_home.scss, app/views/hens/show.html.erb, app/views/pages/home.html.erb
Pouvez-vous checker mon carrousel please ? :)
=> corrige carrousel

app/controllers/hens_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/hen.rb, app/views/hens/index.html.erb, db/seeds.rb, package.json, yarn.lock
We added the search bar to geolocalize the hens.
=> poule localisee + carte

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_home.scss, app/views/hens/edit.html.erb, app/views/hens/new.html.erb, app/views/reservations/new.html.erb
=> frontend formulaire ok

app/controllers/hens_controller.rb, app/models/hen.rb, app/views/hens/edit.html.erb, app/views/hens/new.html.erb, db/migrate/20191128152705_change_hen_city.rb, db/schema.rb, db/seeds.rb
we changed the hens' city to 'address' and added a functioning searchbar
=> Change address

app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> link to index ok

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss
=> indexencours

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, db/migrate/20191128172001_add_photo_to_users.rb, db/schema.rb
On a ajouté une photo à l'utilisateur à l'inscription
=> Avatar user

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/views/hens/index.html.erb
Check the front index and card link!
=> front index ok et lien card ok

app/controllers/hens_controller.rb, app/views/hens/show.html.erb
=> show marker ok

app/controllers/reservations_controller.rb, app/models/reservation.rb, app/views/hens/show.html.erb
we made it impossible to book the same hen at the same time multiple times !
=> validated the reservations validation

db/seeds.rb
=> seed hen modified with address

app/assets/stylesheets/components/_map.scss, app/controllers/hens_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/hens/_info_window.html.erb
=> added the popups to the map
